AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AMI:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for the EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
